#!/bin/bash

# Nombre del archivo de log en la raíz del proyecto
ARCHIVO_LOGS="commits.log"

echo "✓ Commit realizado con éxito."

# Guardar mensaje del último commit en un log
# Formato: [Fecha/Hora] - Hash corto - Autor
echo $(git log -1 --pretty=format: "[%ci] - %h - Autor: %an") >> "$ARCHIVO_LOGS"

exit 0