name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - feature/**

jobs:
  test_build_deploy:
    name: Ejecutar tests, construir Docker y desplegar
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clona el código del repositorio
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      # 2️⃣ Instala Python
      - name: Configurar entorno Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # compatible con Bandit y pytest

      # 3️⃣ Instala dependencias del backend
      - name: Instalar dependencias
        run: |
          cd backend
          pip install -r requirements.txt
          

      # 4️⃣ Ejecuta tests
      - name: Ejecutar tests con pytest
        run: |
          cd backend
          pytest -v --maxfail=1 --disable-warnings

      # 6️⃣ Construye la imagen Docker
      - name: Construir imagen Docker
        run: |
          cd backend
          docker build -t app-citas-medicas:latest .

      # 7️⃣ Simula el despliegue
      - name: Simular despliegue en contenedor
        run: |
          echo "🚀 Desplegando contenedor app-citas-medicas..."
          docker run -d -p 8000:8000 app-citas-medicas:latest
          echo "✅ Contenedor ejecutándose correctamente."
